name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.4
        with:
          deno-version: v2.7.14

      - name: Check
        run: deno task check
