name: Update README

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.4
        with:
          deno-version: v2.7.14

      - name: Run update script
        run: deno task update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERPER_TOKEN: ${{ secrets.SERPER_TOKEN }}

      - name: Format generated files
        run: deno fmt README.md repositories.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":card_file_box: Update README: $(date +'%Y-%m-%d')" || exit 0
          git push
